[package]
name = "bitvmx-bitcoin-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19"
thiserror = "1.0.63"
serde = { version = "1.0.205", features = ["derive"] }

#TODO: Check if this can be in dev-dependencies or as feature
mockall = "0.13.0"
